sudo: required
language: generic
services:
 - docker
env:
 - HHVM_VERSION=latest
 - HHVM_VERSION=nightly
install:
 - docker pull hhvm/hhvm:$HHVM_VERSION
script:
 - docker run -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION /var/source/.travis.sh
